### ISSUE TITLE
Only three LED are showing static color. 

### ISSUE THREAD

**Issue by dawiinci** [awawa-dev/HyperSerialEsp8266#13]
The setup worked with WLED, but because of performance issues I want to try serial connection. 

I use a ESP8266 Nodemcu V3 developer board. This should have the faster chip necessary for 2Mbps. 

Now only the first three leds are glowing static(white and green). 

I flashed the latest image 5.0.0.0 and I use HyperHDR 18.0.0.0. The installation is on a Mac. 

I simply connected the usb to the Mac, flashed and configured in HyperHDR. I can’t change the leds at all. 

LEDs are SK6812 RGBNW. 

Status LED on board is not glowing but flash reported success.

**Comment by dawiinci** [comment]
It did finally work with 1500000. 

I also wanted to use LUT, but I can’t upload it and if I store it in the config folder (outside db)I don’t see it being loaded in the log.

**Comment by awawa-dev** [comment]
> vertical and horizontal pixel depth  

?

> I also wanted to use LUT, but I can’t upload it and if I store it in the config folder (outside db)I don’t see it being loaded in the log.

paste output of the command  ````ls -lah```` run from inside .hyperhdr folder and HyperHDR's logs where the application is outputting all the LUT path combinations which it tries to load (if HDR mode is ENABLED)

**Comment by dawiinci** [comment]
Under advanced in LED configuration. 

I do get green backlight on black scenes and more critical there is a memory leak leading to 16 GB RAM usage on M1 Mac. 

It is possibly related to the Baud rate of 1500000 instead of 1000000.
