### ISSUE TITLE
Python sample for woking with hyperserial

### ISSUE THREAD

**Issue by tihoangyeudau** [awawa-dev/HyperSerialEsp8266#33]
could you please provide us a sample base on python platform that can work with your hyperserial? Thank you

**Comment by awawa-dev** [comment]
Hi
Take a look into this attached Python client that implements correctly classic Fletcher checksum: https://github.com/espressif/arduino-esp32/issues/7505 That part was not implemented correctly in the example you provided before. BTW please use discussion section to make such request.

**Comment by tihoangyeudau** [comment]
@awawa-dev please give me your email. I would like to hire you write a little code for my project. thank you

**Comment by awawa-dev** [comment]
You can find my email address on my Github Profile: https://github.com/awawa-dev

**Comment by tihoangyeudau** [comment]
I have sent you a email
